---
name: design-system
description: Extract and maintain design system components (optional)
author: "Whiteport Design Studio"
phase: 5
web_bundle: true
standalone: true
primary_agent: "freya-ux"
version: 1.0.0

trigger:
  - Called from Phase 4 component specification
  - Only active if design system enabled in project
  - First component triggers initialization

entry_point: design-system-router.md

outputs:
  - D-Design-System/components/*.md
  - D-Design-System/design-tokens.md
  - D-Design-System/component-library-config.md
---
