---
name: WDS Workflow Status
description: Check WDS project progress - answers 'what should I do now?' for any agent
web_bundle: true
---
# WDS Workflow Status - Progress Checker
name: wds-workflow-status
author: "Whiteport Design Studio"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/wds/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/{bmad_folder}/wds/workflows/workflow-status"
instructions: "{installed_path}/instructions.md"

# Status file location
default_output_file: "{output_folder}/wds-workflow-status.yaml"

standalone: true
web_bundle: false
